TOOL_VERSION_INFO_DIR = "results/tool-version-info"
SHELLCODE_OUTPUT_DIR = "shellcode"

DEFAULT_FILE_LOCATION = "default_file"
MAX_HEADER_LEVEL = 6
MIN_HEADER_LEVEL = 1
TABLE_OF_CONTENT_LINE_POSITION = 7
